/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadDataRouteImport } from './routes/uploadData'
import { Route as IndexRouteImport } from './routes/index'

const UploadDataRoute = UploadDataRouteImport.update({
  id: '/uploadData',
  path: '/uploadData',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/uploadData'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/uploadData'
  id: '__root__' | '/' | '/uploadData'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadDataRoute: typeof UploadDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploadData': {
      id: '/uploadData'
      path: '/uploadData'
      fullPath: '/uploadData'
      preLoaderRoute: typeof UploadDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadDataRoute: UploadDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
