/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadDataRouteImport } from './routes/uploadData'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ManageDataRouteImport } from './routes/manageData'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const UploadDataRoute = UploadDataRouteImport.update({
  id: '/uploadData',
  path: '/uploadData',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDataRoute = ManageDataRouteImport.update({
  id: '/manageData',
  path: '/manageData',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manageData': typeof ManageDataRoute
  '/register': typeof RegisterRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manageData': typeof ManageDataRoute
  '/register': typeof RegisterRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manageData': typeof ManageDataRoute
  '/register': typeof RegisterRoute
  '/uploadData': typeof UploadDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/manageData' | '/register' | '/uploadData'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/manageData' | '/register' | '/uploadData'
  id: '__root__' | '/' | '/login' | '/manageData' | '/register' | '/uploadData'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ManageDataRoute: typeof ManageDataRoute
  RegisterRoute: typeof RegisterRoute
  UploadDataRoute: typeof UploadDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploadData': {
      id: '/uploadData'
      path: '/uploadData'
      fullPath: '/uploadData'
      preLoaderRoute: typeof UploadDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manageData': {
      id: '/manageData'
      path: '/manageData'
      fullPath: '/manageData'
      preLoaderRoute: typeof ManageDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ManageDataRoute: ManageDataRoute,
  RegisterRoute: RegisterRoute,
  UploadDataRoute: UploadDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
